"use client";

import { useEffect, useState } from "react";

type Analytics = {
  totalRequests: number;
  cpuRequests: number;
  averageLatencyMs: number;
  lastLatencyMs: number;
  outputCharsPerSecond: number;
};

export default function Page() {
  const [prompt, setPrompt] = useState("Explain why CPU inference can be good enough for some hackathon apps.");
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(false);
  const [analytics, setAnalytics] = useState<Analytics | null>(null);

  async function refreshAnalytics() {
    const response = await fetch("/api/analytics");
    setAnalytics(await response.json());
  }

  async function send() {
    setLoading(true);
    setAnswer("");
    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt, maxTokens: 256 }),
      });
      const data = await response.json();
      setAnswer(data.text || data.error || "No response");
      await refreshAnalytics();
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    refreshAnalytics();
  }, []);

  return (
    <main>
      <section className="toolbar">
        <div>
          <h1>Direct CPU Chat</h1>
          <p>Calls the CPU inference endpoint generated by OCI Inference Cloud.</p>
        </div>
      </section>
      <section className="grid">
        <div className="panel chat">
          <textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} />
          <button onClick={send} disabled={loading}>{loading ? "Sending..." : "Send to CPU endpoint"}</button>
          <pre>{answer}</pre>
        </div>
        <div className="panel">
          <h2>Analytics</h2>
          <Metric label="Total requests" value={analytics?.totalRequests || 0} />
          <Metric label="CPU requests" value={analytics?.cpuRequests || 0} />
          <Metric label="Average latency" value={`${(analytics?.averageLatencyMs || 0).toFixed(0)} ms`} />
          <Metric label="Last latency" value={`${(analytics?.lastLatencyMs || 0).toFixed(0)} ms`} />
          <Metric label="Output chars/sec" value={(analytics?.outputCharsPerSecond || 0).toFixed(1)} />
        </div>
      </section>
    </main>
  );
}

function Metric({ label, value }: { label: string; value: string | number }) {
  return <div className="metric"><span>{label}</span><strong>{value}</strong></div>;
}
